# Generated by Django 5.2.1 on 2025-06-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('brand_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('color_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('location_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subdivision', models.CharField(max_length=30)),
                ('lot_block', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('wire_type_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('wire_type_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WireSku',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('feet', models.IntegerField()),
                ('typical_cost', models.FloatField()),
                ('cost_per_foot', models.FloatField()),
                ('brand_id', models.ForeignKey(default='BRAND UNASSIGNED', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.brand')),
                ('color_id', models.ForeignKey(default='COLOR UNASSIGNED', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.color')),
                ('wire_type_id', models.ForeignKey(default='TYPE UNASSIGNED', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.wiretype')),
            ],
        ),
        migrations.CreateModel(
            name='WireBox',
            fields=[
                ('wire_box_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('purchase_cost', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('disposed_date', models.DateField(null=True)),
                ('disposed_feet_rem', models.DateField(null=True)),
                ('location_id', models.ForeignKey(default='Warehouse', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiresku')),
            ],
        ),
        migrations.CreateModel(
            name='WireUsage',
            fields=[
                ('wire_usage_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('start_feet', models.IntegerField()),
                ('end_feet', models.IntegerField()),
                ('date_used', models.DateField()),
                ('project_id', models.ForeignKey(default='PROJECT UNASSIGNED', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.project')),
                ('wire_box_id', models.ForeignKey(default='BOX UNASSIGNED', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.wirebox')),
            ],
        ),
    ]
