# Generated by Django 5.2.1 on 2025-06-28 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lot_block',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subdivision',
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='CLIENT NAME NOT PROVIDED', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='PROJECT NAME NOT PROVIDED', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wirebox',
            name='wire_box_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='wire_type_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wireusage',
            name='wire_usage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
