# Generated by Django 5.2.1 on 2025-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_client_remove_project_lot_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='CLIENT NAME NOT PROVIDED', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='PROJECT NAME NOT PROVIDED', max_length=200, primary_key=True, serialize=False),
        ),
    ]
