# Generated by Django 5.2.1 on 2025-07-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_client_name_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiresku',
            name='cost_per_foot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
