# Generated by Django 5.2.1 on 2025-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wiresku_cost_per_foot'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiresku',
            name='sku_desc',
            field=models.CharField(default='DESCRIPTION NOT GIVEN', max_length=50),
        ),
    ]
