# Generated by Django 5.2.1 on 2025-07-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wiresku_sku_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirebox',
            name='disposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wirebox',
            name='disposed_feet_rem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wirebox',
            name='location_id',
            field=models.ForeignKey(default='shelf', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.location'),
        ),
    ]
