# Generated by Django 5.2.1 on 2025-07-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_wirebox_disposed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirebox',
            name='purchase_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wirebox',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wirebox',
            name='wire_box_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
